# Generated by Django 6.1 on 2026-09-02 17:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habbit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=255)),
                ("time", models.TimeField()),
                ("action", models.CharField(max_length=255)),
                ("is_pleasant", models.BooleanField(default=False)),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "execution_time",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(120)]
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habbits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_habbit",
                    models.ForeignKey(
                        blank=True,
                        null=-1,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pleasant_for",
                        to="habbits.habbit",
                    ),
                ),
            ],
        ),
    ]
