# Generated by Django 6.0.8 on 2026-09-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habbit",
            name="last_reminded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
